"""DSL (Domain Specific Language) module for scene graph representation."""

from backend.dsl.schema import (
    BoundingBox,
    Canvas,
    Effects,
    Fill,
    GenerateRequest,
    GenerateResponse,
    GradientFill,
    GradientStop,
    PathCommand,
    Shadow,
    Shape,
    ShapeType,
    SlideMetadata,
    SlideScene,
    SolidFill,
    Stroke,
    TextContent,
    TextRun,
    ThemeColors,
    Transform,
)

__all__ = [
    "BoundingBox",
    "Canvas",
    "Effects",
    "Fill",
    "GenerateRequest",
    "GenerateResponse",
    "GradientFill",
    "GradientStop",
    "PathCommand",
    "Shadow",
    "Shape",
    "ShapeType",
    "SlideMetadata",
    "SlideScene",
    "SolidFill",
    "Stroke",
    "TextContent",
    "TextRun",
    "ThemeColors",
    "Transform",
]
